# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  node:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:12.22.7
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Check node and yarn version
          command: |
            echo "node: `node -v`"
            echo "yarn: v`yarn -v`"

      - run:
          name: Install dependences
          command: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Build package
          command: yarn build

      - run:
          name: Run test
          command: yarn test --watchAll=false

      - persist_to_workspace:
          root: ~/react-app
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  version: 2
  node:
    jobs:
      - node
